// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
namespace Darkhexxa
{
	using Core;
	namespace SimplePool
	{
        /**
          * @brief empty list class used to destinguash the pool lists from another list the objects might be in.
          */
        [AddComponentMenu("DarkHexxa/SimplePool/Components/Pool Listable Component")]
		public class PoolListableComponent : ListableComponent
		{
		}
	}
}

