// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using UnityEngine;
using System.Collections;

namespace Darkhexxa
{
	namespace SimplePool
	{
		using Core;
		namespace Components
		{
            /**
              * @brief Abstact Base class for GameObjects created by pools.
              */
			public abstract class BasePoolComponent : MonoBehaviour
			{
				private SimplePool _pool;

                /**
                  * @b the pool component that spawned this object.
                  */
				public SimplePool pool {
					get
					{
						return _pool;
					}
				}

                /**
                  * @b function called by SimplePool when an object is cloned.
                  * 
                  * Allows code to be implemented when this object is added to the scene but is not yet active.
                  * 
                  * @param the simple pool that created this object.
                  */
				public void OnCreatedByPool( SimplePool pool )
				{
					_pool = pool;
				}

                /**
                  * @b abstract function that is called when the object is spawned and becomes active.
                  */
				public abstract void OnSpawn();
                /**
                  * @b abstract function that is called when the object is removed and becomes inactive.
                  */
				public abstract void OnDespawn();
			}
		}
	}
}

