//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using System.Collections;

namespace Darkhexxa
{
    namespace Core
    {
        public abstract class ListableComponent : MonoBehaviour
        {

            private ListableComponent _previous = null;
            private ListableComponent _next = null;

			private ComponentList _list = null;

			public ComponentList list
			{
				get
				{
					return _list;
				}
				set
				{
					_list = value;
				}
			}

            public ListableComponent Previous
            {
                get
                {
                    return _previous;
                }
                set
                {
                    _previous = value;
                }
            }

            public ListableComponent Next
            {
                get
                {
                    return _next;
                }
                set
                {
                    _next = value;
                }
            }

			void OnDestroy()
			{
				if (list != null)
				{
					list.Remove(this.gameObject);
				}
			}

        }
    }
}


